config/routes.rb
Rails.application.routes.draw do
  root "pages#show", page: 'home'
  get '/pages/:page', to: 'pages#show'

  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]

  get '/observations/new', to: 'observations#new_new'
  post '/observations', to: 'observations#create_new'


  resources :patients, shallow: true do
    resources :observations do
      resources :comments
    end
  end

  get '/observations/:observation_id/like', to: 'users#like', as: :like
  get '/observations/:observation_id/unlike', to: 'users#unlike', as: :unlike

  resources :sessions, only: [:new, :create, :destroy]
  post '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

end

app/models/observation.rb
class Observation < ActiveRecord::Base
  belongs_to :patient
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :liking_users, through: :likes, source: :user
end

app/controllers/observations_controller.rb
class ObservationsController < ApplicationController

  def index
    @observations = Observation.all
  end

  def new
    @observation = Observation.new
    @patient = Patient.find(params[:patient_id])
  end

  def create
    @patient = Patient.find(params[:patient_id])
    @observation = Observation.new(ob_params)
    @observation.patient = @patient
    @observation.user = current_user
    if @observation.save
      redirect_to @patient
    else
      render :new
    end
  end

  def new_new
    @observation = Observation.new
  end

  def create_new
    @observation = Observation.new(params.require(:observation).permit(:patient_id, :user_id, :date, :goal, :program, :prompt, :behavior, :session_notes))
    @patient = @observation.patient
    @observation.user = current_user
    if @observation.save
      redirect_to patients_path
    else
      render :new_new
    end
  end

  def show
    @observation = Observation.find(params[:id])
    @comment = Comment.new
    @my_comments = @observation.comments.where(user_id: current_user.id)
  end

  def edit
    @observation = Observation.find(params[:id])
  end

  def update
    @observation = Observation.find(params[:id])
    @observation.update_attributes(ob_params)
    redirect_to @observation
  end

  def destroy
    @observation = Observation.find(params[:id])
    @patient = @observation.patient
    @observation.destroy
    redirect_to @patient
  end

  private
  def ob_params
    params.require(:observation).permit(:date, :goal, :program, :prompt, :behavior, :session_notes)
  end

end

app/views/observations/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="text-center">Edit Observation for <%= @observation.patient.first_name %></h1>
      <hr>
      <%= form_for [@patient, @observation] do |f| %>
      <div class="field form-group">
        <%= f.label :date %>
        <%= f.date_field :date, :value => Date.today, class: 'form-control', :required => true %>
      </div>
      <div class="field form-group">
        <%= f.label :goal %>
        <%= f.text_field :goal, class: 'form-control', :required => true %>
      </div>
      <div class="field form-group">
        <%= f.label :program, 'Target Program' %>
        <%= f.text_field :program, class: 'form-control', :required => true %>
      </div>
      <div class="field form-group">
        <%= f.label :prompt %>
        <%= f.text_field :prompt, class: 'form-control' %>
      </div>
      <div class="field form-group">
        <%= f.label :behavior %>
        <%= f.text_field :behavior, class: 'form-control' %>
      </div>
      <div class="field form-group">
        <%= f.label :session_notes %>
        <%= f.text_area :session_notes, class: 'form-control', :required => true %>
      </div>
      <%= f.submit "Save", class: 'btn btn-default' %>
      <%= link_to "Cancel", @observation, class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>
</div>

app/views/observations/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="text-center">New Observation for <%= @patient.first_name %> </h1>
      <hr>
      <%= form_for [@patient, @observation] do |f| %>
      <div class="field form-group">
        <%= f.label :date %>
        <%= f.date_field :date, :value => Date.today, class: 'form-control', :required => true %>
      </div>
      <div class="field form-group">
        <%= f.label :goal %>
        <%= f.text_field :goal, :value => current_user.field, class: 'form-control', :required => true %>
      </div>
      <div class="field form-group">
        <%= f.label :program, 'Target Program' %>
        <%= f.text_field :program, class: 'form-control', :required => true %>
      </div>
      <div class="field form-group">
        <%= f.label :prompt %>
        <%= f.text_field :prompt, class: 'form-control' %>
      </div>
      <div class="field form-group">
        <%= f.label :behavior %>
        <%= f.text_field :behavior, class: 'form-control' %>
      </div>
      <div class="field form-group">
        <%= f.label :session_notes %>
        <%= f.text_area :session_notes, class: 'form-control', :required => true %>
      </div>
      <div class="actions">
      <%= f.submit "Save", class: 'btn btn-default' %>
      <%= link_to "Cancel", patient_path(@patient), class: 'btn btn-default'%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/observations/new_new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="text-center">New Observation</h1>
      <hr>
      <%= form_for [@patient, @observation] do |f| %>
      <div class="form-group">
        <%= f.label :patient %>
        <%= f.collection_select(:patient_id, Patient.all, :id, :first_name, prompt: true)%>
      </div>
      <div><%= link_to 'Patient not listed?', new_patient_path %></div>
      <div class="form-group">
        <%= f.label :date %>
        <%= f.date_field :date, :value => Date.today, class: 'form-control', :required => true %>
      </div>
      <div class="form-group">
        <%= f.label :goal %>
        <%= f.text_field :goal, :value => current_user.field, class: 'form-control', :required => true %>
      </div>
      <div class="form-group">
        <%= f.label :program, 'Target Program' %>
        <%= f.text_field :program, class: 'form-control', :required => true %>
      </div>
      <div class="form-group">
        <%= f.label :prompt %>
        <%= f.text_field :prompt, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :behavior %>
        <%= f.text_field :behavior, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :session_notes %>
        <%= f.text_area :session_notes, class: 'form-control', :required => true %>
      </div>
      <div class="actions">
        <%= f.submit "Save", class: 'btn btn-default' %>
        <%= link_to "Cancel", patients_path, class: 'btn btn-default' %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/observations/show.html.erb
<hr>
<div class="text-center">
<% if @observation.user == current_user %>
  <%= link_to 'Edit', edit_observation_path %>
  &nbsp; | &nbsp;
  <%= link_to "Delete Observation", observation_path(@observation), method: :delete, data: {confirm: 'Are you sure?'} %>
  &nbsp; | &nbsp;
  <%= link_to "Back to Patient", patient_path(@observation.patient) %>
  <% else %>
  <%= link_to "Back to Patient", patient_path(@observation.patient) %>
  <% end %>
</div>
<br>

<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">
  <!-- Default panel contents -->
      <div class="panel-heading">
        <%= @observation.goal %> with <%= @observation.user.first_name %> on <%= @observation.date %>
      </div>
      <div class="panel-body">
        <p>
          Date: <%= @observation.date.strftime("%m/%d/%Y") %>
        <br>
          Goal: <%= @observation.goal %>
        <br>
          Program: <%= @observation.program %>
        <br>
          Prompt(s): <%= @observation.prompt %>
        <br>
          Behavior(s): <%= @observation.behavior %>
        <br>
          Session Notes: <%= @observation.session_notes %>
        <br>
        </p>
        <div class="panel-bottom pull-right">
          <% if @observation.likes.count > 0 %>
            <% if @observation.likes.count > 1 %>
              <span> <%= @observation.likes.count %> likes </span> &nbsp;&nbsp;&nbsp;
            <% else %>
              <span> <%= @observation.likes.count %> like </span> &nbsp;&nbsp;&nbsp;
            <% end %>
          <% end %>
            <% if current_user.like?(@observation.id) %>
              <%= link_to "", unlike_path(@observation), class: "glyphicon glyphicon-thumbs-down" %>
            <% else %>
              <%= link_to "", like_path(@observation), class: "glyphicon glyphicon-thumbs-up" %>
            <% end %>
        </div>
      </div>

  <!-- List group -->
      <ul class="list-group">
        <% @observation.comments.each do |c| %>
          <li class="list-group-item">
            <%= c.content %> <br><br>
            @<%= link_to c.user.first_name, user_path(c.user.id) %>
            added <%= time_ago_in_words(c.created_at) %> ago
            <% if c.user == current_user %>
              <span>
                <%= link_to '', comment_path(c), method: :delete, data: {confirm: 'Are you sure?'}, class: 'glyphicon glyphicon-trash pull-right' %>
              </span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>

      <%= form_for [@observation, @comment] do |f| %>
      <span class="field form-group">
        <%= f.text_area :content, class: 'form-control', :required => true %>
      </span>
      <span class="actions">
        <%= f.submit "Add Comment", class: 'btn btn-primary', id: 'comment-button' %>
      </span>
      <% end %>
    </div>
  </div>
</div>