config/routes.rb
Rails.application.routes.draw do
  root "pages#show", page: 'home'
  get '/pages/:page', to: 'pages#show'

  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]

  get '/observations/new', to: 'observations#new_new'
  post '/observations', to: 'observations#create_new'


  resources :patients, shallow: true do
    resources :observations do
      resources :comments
    end
  end

  get '/observations/:observation_id/like', to: 'users#like', as: :like
  get '/observations/:observation_id/unlike', to: 'users#unlike', as: :unlike

  resources :sessions, only: [:new, :create, :destroy]
  post '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, uniqueness: true

  has_attached_file :image, styles: { medium: "500x500>", thumb: "250x250>" }, presence: true
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  has_many :observations, dependent: :destroy
  has_many :patients, through: :observations
  has_many :comments
  has_many :likes
  has_many :liked_observations, through: :likes, source: :observation

  def like!(observation_id)
    self.likes.create(observation_id: observation_id)
  end

  def unlike!(observation_id)
    like = self.likes.find_by(observation_id: observation_id)
    like.destroy
  end

  def like?(observation_id)
    self.likes.find_by(observation_id: observation_id)
  end

  private
  def set_defaults
    self.image = "/:attachment/:style/missing.png" if self.image.nil?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      # flash[:notice] = "You successfully signed up!"
      redirect_to patients_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def like
    current_user.like!(params[:observation_id]) unless current_user.like?(params[:observation_id])
    redirect_to :back
  end

  def unlike
    current_user.unlike!(params[:observation_id]) if current_user.like?(params[:observation_id])
    redirect_to :back
  end

  private
   def user_params
      params.require(:user).permit(:first_name, :last_name, :role, :location, :sector, :email, :password, :password_confirmation, :image)
   end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="text-center">Edit Account</h1>
      <hr>
      <%= form_for @user, html: { multipart: true } do |f| %>
        <% if @user.errors.any? %>
          <div class="error_messages">
            <h2>Form is invalid</h2>
            <ul>
              <% for message in @user.errors.full_messages %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="field form-group">
          <%= f.label 'Upload Profile Picture' %>
          <%= f.file_field :image %>
        </div>
        <div class="field form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, :required => true, class: 'form-control' %>
        </div>
        <div class="field form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, :required => true, class: 'form-control' %>
        </div>
        <div class="field form-group">
          <%= f.label :field %>:
          <%= f.select :field, ['Audiology', 'Occupational Therapy', 'Psychology', 'Speech Language Pathology', 'Special Education', 'Physical Therapy'], :prompt => 'Select One', :required => true, class: 'form-control' %>
        </div>
        <div class="field form-group">
          <%= f.label :role %>:
          <%= f.select :role, ['Audiologist', 'Occupational Therapist', 'Psychologist', 'Speech Language Pathologist', 'Teacher', 'Physical Therapist'], :prompt => 'Select One', :required => true, class: 'form-control' %>
        </div>
        <div class="field form-group">
          <%= f.label :location %>
          <%= f.text_field :location, :required => true, class: 'form-control' %>
        </div>
        <div class="field form-group">
        Select one:
          <%= f.radio_button :sector, "private" %>
          <%= f.label :sector_private, "I work in the private sector" %>
          <%= f.radio_button :sector, "public" %>
          <%= f.label :sector_public, "I work in the public sector" %>
        </div>
        <div class="field form-group">
          <%= f.label :email %>
          <%= f.email_field :email, :required => true, class: 'form-control' %>
        </div>
        <div class="field form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="field form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <div class="actions"><%= f.submit "Save changes", class: 'btn btn-default'%>
        <%= link_to "Back to Profile", user_path, class: 'btn btn-default' %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="text-center">Create an Account</h1>
      <hr>
      <%= form_for @user, html: { multipart: true } do |f| %>
        <% if @user.errors.any? %>
          <div class="error_messages">
            <h2>Form is invalid</h2>
            <ul>
              <% for message in @user.errors.full_messages %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="field form-group">
          <%= f.label 'Upload Profile Picture' %>
          <%= f.file_field :image %>
        </div>
        <div class="field form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, :required => true, class: 'form-control' %>
        </div>
        <div class="field form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, :required => true, class: 'form-control' %>
        </div>
        <div class="field form-group">
          <%= f.label :field %>:
          <%= f.select :field, ['Audiology', 'Occupational Therapy', 'Psychology', 'Speech Language Pathology', 'Special Education', 'Physical Therapy'], :prompt => 'Select One', :required => true, class: 'form-control' %>
        </div>
        <div class="field form-group">
          <%= f.label :role %>:
          <%= f.select :role, ['Audiologist', 'Occupational Therapist', 'Psychologist', 'Speech Language Pathologist', 'Teacher', 'Physical Therapist'], :prompt => 'Select One', :required => true, class: 'form-control' %>
        </div>
        <div class="field form-group">
          <%= f.label :location %>
          <%= f.text_field :location, :required => true, class: 'form-control' %>
        </div>
        <div class="field form-group">
        Select one:
          <%= f.radio_button :sector, "Private" %>
          <%= f.label :sector_private, "I work in the private sector" %>
          <%= f.radio_button :sector, "Public" %>
          <%= f.label :sector_public, "I work in the public sector" %>
        </div>
        <div class="field form-group">
          <%= f.label :email %>
          <%= f.email_field :email, :required => true, class: 'form-control' %>
        </div>
        <div class="field form-group">
          <%= f.label :password %>
          <%= f.password_field :password, :required => true, class: 'form-control' %>
        </div>
        <div class="field form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, :required => true, class: 'form-control' %>
        </div>
        <div class="actions">
          <%= f.submit "Create User", class: 'btn btn-default' %>
          <%= link_to "Cancel", root_path, class: 'btn btn-default' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="jumbotron">
  <div class="container text-center">
    <h1 class="text-center"><%= @user.first_name %> <%= @user.last_name %></h1>
    <br>
    <%= image_tag @user.image.url, class:'img-responsive rounded image-cropper'%>
    <br>
    <div>
      Role: <%= @user.role %>
      <br>
      Location: <%= @user.location %>
      <br>
      Sector(s): <%= @user.sector %>
      <br>
      Email: <%= mail_to @user.email %>
      <br>
    </div>
    <br>
    <% if @user == current_user %>
      <span><%= link_to 'Edit Profile', edit_user_path, class: 'btn btn-default'%></span>
      <span><%= link_to "Back to Dashboard", patients_path, class: 'btn btn-default'%></span>
    <% else %>
      <span><%= link_to "Back to Dashboard", patients_path, class: 'btn btn-default'%></span>
    <% end %>
  </div>
</div>