config/routes.rb
Rails.application.routes.draw do
  root "pages#show", page: 'home'
  get '/pages/:page', to: 'pages#show'

  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]

  get '/observations/new', to: 'observations#new_new'
  post '/observations', to: 'observations#create_new'


  resources :patients, shallow: true do
    resources :observations do
      resources :comments
    end
  end

  get '/observations/:observation_id/like', to: 'users#like', as: :like
  get '/observations/:observation_id/unlike', to: 'users#unlike', as: :unlike

  resources :sessions, only: [:new, :create, :destroy]
  post '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "500x500>", thumb: "250x250>" }, presence: true
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  has_many :observations
  has_many :users, through: :observations

  # def self.search(search)
  #   if search
  #     where("first_name LIKE ?", "%#{search}%")
  #   else
  #     current_user.patients.distinct
  #   end
  # end

  # def self.search(search)
  #   if search
  #     Patient.all.where("LOWER(first_name) LIKE ?", "%#{search}%".downcase)
  #   else
  #     @my_patients
  #   end
  # end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  def index
    # @my_patients = current_user.patients.distinct
    # @my_patients = current_user.patients.search(params[:search])
    # @patients = Patient.search(params[:search])
    # @my_patients = Patient.search(params[:search])
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      flash[:warning] = 'Patient has been created. NOTE: This patient has not been added to your caseload. Please create an observation.'
      redirect_to @patient
    else
      render :new
    end
  end

  def show
    @patient = Patient.find(params[:id])
    @my_obs = current_user.observations.where(patient_id: @patient.id)
    @other_obs = @patient.observations.where.not(user_id: current_user.id)
    @users = @patient.users.all
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    @patient.update_attributes(patient_params)
    redirect_to @patient
  end

  def destroy
    @patient = Patient.find(params[:id])
    current_user.observations.where(patient_id: @patient).destroy_all
    @patient.destroy if @patient.observations.count == 0
    redirect_to patients_path
  end

  private
  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :age, :gender, :diagnosis, :parent, :parent_email, :home_session, :school_session, :image)
  end

end

app/views/patients/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="text-center">Update Patient</h1>
      <hr>
      <%= form_for @patient do |f| %>
        <div class="field form-group">
          <%= f.label 'Upload Profile Picture' %>
          <%= f.file_field :image %>
        </div>
        <div class="field form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: 'form-control', :required => true %>
        </div>
        <div class="field form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: 'form-control', :required => true %>
        </div>
        <div class="field form-group">
          <%= f.label :diagnosis %>
          <%= f.text_field :diagnosis, :required => true, class: 'form-control' %>
        </div>
        <div class="field form-group">
          <%= f.label :age %>
          <%= f.text_field :age, class: 'form-control', :required => true %>
        </div>
        <div class="field form-group">
          <%= f.label :gender %>
          <%= f.select :gender, ['Female', 'Male', 'Do not disclose'], :prompt => 'Select One:', class: 'form-control', :required => true %>
        </div>
        <div class="field form-group">
          <%= f.label :parent %>
          <%= f.text_field :parent, :required => true, class: 'form-control' %>
        </div>
        <div class="field form-group">
          <%= f.label :parent_email %>
          <%= f.email_field :parent_email, :required => true, class: 'form-control' %>
        </div>
        <div class="field form-group">
        Select all that apply:
        <br>
          <%= f.check_box :home_session %>
          <%= f.label :home_session %>
          <br>
          <%= f.check_box :school_session %>
          <%= f.label :school_session %>
        </div>
        <%= f.submit "Update Patient", class: 'btn btn-default'%> <%= link_to "Cancel", patient_path(@patient), class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>
</div>

app/views/patients/index.html.erb
<div class="jumbotron">
  <div class="container text-center">
    <h1>Caseload</h1>
    <br>
    <%= link_to 'Create Observation for New Patient', observations_new_path, class: 'btn btn-primary'%>
  </div>
</div>

<%# if current_user.patients.distinct.count > 3 %>
  <%#= form_tag patients_path, method: :get, class: "navbar-form pull-right", role: "search" do %>
    <!-- <div class="form-group form-inline">
      <%#= text_field_tag :search, params[:search], class: "form-control", placeholder: "Patient's Name" %>
      <%#= submit_tag "Search", :name => nil, class: "btn btn-default", id: 'search-button' %>
    </div> -->
  <%# end %>
<%# end %>

<hr>
 <!-- Caseload Grid Section -->
<div class="container">
  <section id="caseload">
    <div class="row">
    <% current_user.patients.distinct.each do |p| %>
        <div class="col-xs-3 text-center caseload-item">
          <div class="image-cropper" id="index-pic">
            <%= link_to (image_tag(p.image.url)), patient_path(p) %>
          </div>
            <%= p.first_name %>
            <%= p.last_name %>
          <br>
        </div>
    <% end %>
    </div>
  </section>
</div>

app/views/patients/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1 class="text-center">Create New Patient</h1>
      <hr>
      <%= form_for @patient do |f| %>
        <div class="field form-group">
          <%= f.label 'Upload Profile Picture' %>
          <%= f.file_field :image %>
        </div>
        <div class="field form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: 'form-control', :required => true %>
        </div>
        <div class="field form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: 'form-control', :required => true %>
        </div>
        <div class="field form-group">
          <%= f.label :diagnosis %>
          <%= f.text_field :diagnosis, :required => true, class: 'form-control' %>
        </div>
        <div class="field form-group">
          <%= f.label :age %>
          <%= f.text_field :age, class: 'form-control', :required => true %>
        </div>
        <div class="field form-group">
          <%= f.label :gender %>
          <%= f.select :gender, ['Female', 'Male', 'Do not disclose'], :prompt => 'Select One:', class: 'form-control', :required => true %>
        </div>
        <div class="field form-group">
          <%= f.label :parent %>
          <%= f.text_field :parent, :required => true, class: 'form-control' %>
        </div>
        <div class="field form-group">
          <%= f.label :parent_email %>
          <%= f.email_field :parent_email, :required => true, class: 'form-control' %>
        </div>
        <div class="field form-group">
        Select all that apply:
        <br>
          <%= f.check_box :home_session %>
          <%= f.label :home_session %>
          <br>
          <%= f.check_box :school_session %>
          <%= f.label :school_session %>
        </div>
        <div class="actions">
          <%= f.submit "Submit", class: 'btn btn-default' %>
          <%= link_to 'Cancel', observations_new_path, class: 'btn btn-default'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/patients/show.html.erb
<div class="jumbotron">
  <div class="container text-center">
    <h1 class="text-center"><%= @patient.first_name %> <%= @patient.last_name %></h1>
    <br>
    <%= image_tag @patient.image.url, class:'img-responsive rounded image-cropper' %>
    <%= link_to 'Create New Observation', new_patient_observation_path(@patient), class: 'btn btn-primary'%> &nbsp;
    <%= mail_to @patient.parent_email, 'Contact Parent', class: 'btn btn-primary' %>
  </div>
</div>
<!-- <div class="alert alert-warning" role="alert"> -->
<% flash.each do |message_type, alert| %>
<div class="container">
  <div class="text-center alert alert-<%= message_type%>"><%= alert %></div>
</div>
<% end %>
<hr>
<div class="text-center">
  <%= link_to 'Edit Patient Details', edit_patient_path %> &nbsp; | &nbsp;
  <%= link_to "Delete Patient", patient_path(@patient), method: :delete, data: {confirm: 'Are you sure?'} %> &nbsp; | &nbsp;
  <%= link_to "Back to Dashboard", patients_path %>
</div>
<hr>
<div class="container">
  <div class="row">
    <div class="col-md-3 col-md-offset-2">
    <h3>Patient Details</h3>
      <p>
        Age: <%= @patient.age %>
        <br>
        Gender: <%= @patient.gender %>
        <br>
        Diagnosis: <%= @patient.diagnosis %>
        <br>
        Parent(s): <%= @patient.parent %>
        <br>
        Specialist(s):
        <ul>
        <% @users.distinct.each do |u| %>
          <li><%=link_to u.first_name + u.last_name, user_path(u) %></li>
        <% end %>
        </ul>
        Type of Sessions:
        <br>
        School Session: <%= @patient.school_session %>
        <br>
        Home Session: <%= @patient.home_session %>
      </p>
    </div>

    <div class="col-md-5">
      <h3 class="text-center">List of Observations</h3>
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title">My Observations</h3>
        </div>
        <ul class="list-group">
          <% if @my_obs.count > 0 %>
            <% @my_obs.each do |o| %>
              <li class="list-group-item"><%= link_to o.program, observation_path(o)%> (<%= o.goal %>) on <%= o.date.strftime("%m/%d/%Y") %></li>
            <% end %>
          <% else %>
            <li class="list-group-item">None</li>
          <% end %>
        </ul>
      </div>

      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">Other Observations</h3>
        </div>
        <ul class="list-group">
          <% if @other_obs.count > 0 %>
            <% @other_obs.each do |o| %>
              <li class="list-group-item"><%= link_to o.program, observation_path(o)%> (<%= o.goal %>) on <%= o.date.strftime("%m/%d/%Y") %></li>
            <% end %>
          <% else %>
              <li class="list-group-item">None</li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>