config/routes.rb
Rails.application.routes.draw do
  root "pages#show", page: 'home'
  get '/pages/:page', to: 'pages#show'

  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]

  get '/observations/new', to: 'observations#new_new'
  post '/observations', to: 'observations#create_new'


  resources :patients, shallow: true do
    resources :observations do
      resources :comments
    end
  end

  get '/observations/:observation_id/like', to: 'users#like', as: :like
  get '/observations/:observation_id/unlike', to: 'users#unlike', as: :unlike

  resources :sessions, only: [:new, :create, :destroy]
  post '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CollabApp</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar" id="bar-one"></span>
        <span class="icon-bar" id="bar-two"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
        <span class="glyphicon glyphicon-leaf" aria-hidden="true"></span>&nbsp;
        <span id="app-name">collabPort</span>
      </a>
    </div>
    <p>
      <% if current_user %>
        <p><%= link_to 'Log Out', session_path('dummy'), method: :delete, class: 'navbar-text navbar-right btn btn-default' %></p>
        <p><%= link_to 'View Profile', user_path(current_user), class: 'navbar-text navbar-right', id: 'view-profile-link' %></p>
        <p class="navbar-text navbar-right" id="welcome-profile-link">Welcome, <%= current_user.first_name %>!</p>
      <% end %>
    </p>
  </div>
</nav>



<%= yield %>

</body>
</html>

app/views/layouts/landing_page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CollabApp</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Love+Ya+Like+A+Sister" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="home-page">

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <span class="glyphicon glyphicon-leaf" aria-hidden="true"></span>&nbsp;
        <span id="app-name">collabPort</span>
      </a>
    </div>
  </div>
</nav>

<div></div>

<%= yield %>

</body>
</html>